'use client';

import { useState } from 'react';
import type { Analysis } from '@/lib/types';
import { useAuth } from '@/lib/auth';
import { ScoreRing } from './ScoreRing';
import { AgentTimeline } from './AgentTimeline';
import { AnalysisChat } from './AnalysisChat';
import { Check, X, Copy, CheckCheck, FileText, Mail, Compass, Activity, MessageSquare } from 'lucide-react';

type Tab = 'chat' | 'resume' | 'cover' | 'gaps' | 'steps';

export function AnalysisResults({ analysis }: { analysis: Analysis }) {
  const { user } = useAuth();
  const [tab, setTab] = useState<Tab>('resume');

  const tabs: { key: Tab; label: string; icon: typeof FileText }[] = [
    { key: 'resume', label: 'Tailored resume', icon: FileText },
    { key: 'cover', label: 'Cover letter', icon: Mail },
    { key: 'gaps', label: 'Skill gaps', icon: Compass },
    { key: 'chat', label: 'Ask coach', icon: MessageSquare },
    { key: 'steps', label: 'Agent steps', icon: Activity },
  ];

  return (
    <div className="space-y-6">
      {/* Overview */}
      <div className="card grid gap-6 p-6 md:grid-cols-[auto,1fr] md:items-center">
        <div className="flex justify-center md:justify-start">
          <ScoreRing score={analysis.matchScore ?? 0} />
        </div>
        <div>
          <h2 className="text-xl font-semibold text-ink">
            {analysis.jobTitle || 'Match analysis'}
            {analysis.company ? <span className="text-ink-muted"> · {analysis.company}</span> : null}
          </h2>
          {analysis.summary && (
            <p className="mt-2 text-sm leading-relaxed text-ink-soft">{analysis.summary}</p>
          )}

          <div className="mt-4 grid gap-4 sm:grid-cols-2">
            <KeywordList title="Matched" tone="good" items={analysis.matchedKeywords} />
            <KeywordList title="Missing" tone="bad" items={analysis.missingKeywords} />
          </div>
        </div>
      </div>

      <div>
        <div className="flex flex-wrap gap-1 border-b border-line">
          {tabs.map(({ key, label, icon: Icon }) => (
            <button
              key={key}
              onClick={() => setTab(key)}
              className={`inline-flex items-center gap-2 border-b-2 px-3.5 py-2.5 text-sm font-medium transition-colors ${
                tab === key
                  ? 'border-brand-600 text-ink'
                  : 'border-transparent text-ink-muted hover:text-ink'
              }`}
            >
              <Icon className="h-4 w-4" />
              {label}
            </button>
          ))}
        </div>

        <div className="pt-5">
          {tab === 'resume' && <CopyableText text={analysis.tailoredResume} empty="No tailored resume produced." />}
          {tab === 'cover' && <CopyableText text={analysis.coverLetter} empty="No cover letter produced." />}
          {tab === 'gaps' && <SkillGaps analysis={analysis} />}
          {tab === 'chat' && (
            <AnalysisChat
              analysisId={analysis._id}
              initialChat={analysis.chat ?? []}
              plan={user?.plan ?? 'free'}
            />
          )}
          {tab === 'steps' && (
            <div className="card p-6">
              {analysis.steps.length ? (
                <AgentTimeline steps={analysis.steps} />
              ) : (
                <p className="text-sm text-ink-muted">No steps recorded.</p>
              )}
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

function KeywordList({ title, tone, items }: { title: string; tone: 'good' | 'bad'; items: string[] }) {
  const Icon = tone === 'good' ? Check : X;
  const cls = tone === 'good' ? 'bg-emerald-50 text-emerald-700' : 'bg-rose-50 text-rose-700';
  return (
    <div>
      <p className="mb-2 text-xs font-semibold uppercase tracking-wide text-ink-muted">{title}</p>
      {items.length === 0 ? (
        <p className="text-sm text-ink-muted">—</p>
      ) : (
        <div className="flex flex-wrap gap-1.5">
          {items.map((k) => (
            <span key={k} className={`badge ${cls}`}>
              <Icon className="h-3 w-3" />
              {k}
            </span>
          ))}
        </div>
      )}
    </div>
  );
}

function CopyableText({ text, empty }: { text: string; empty: string }) {
  const [copied, setCopied] = useState(false);
  if (!text) return <p className="text-sm text-ink-muted">{empty}</p>;

  const copy = async () => {
    await navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 1800);
  };

  return (
    <div className="card overflow-hidden">
      <div className="flex items-center justify-between border-b border-line px-4 py-2.5">
        <span className="text-xs font-medium text-ink-muted">Generated by the agent</span>
        <button onClick={copy} className="btn-ghost px-2.5 py-1.5 text-xs">
          {copied ? <CheckCheck className="h-3.5 w-3.5 text-emerald-600" /> : <Copy className="h-3.5 w-3.5" />}
          {copied ? 'Copied' : 'Copy'}
        </button>
      </div>
      <pre className="max-h-[32rem] overflow-auto whitespace-pre-wrap px-5 py-4 font-sans text-sm leading-relaxed text-ink-soft">
        {text}
      </pre>
    </div>
  );
}

function SkillGaps({ analysis }: { analysis: Analysis }) {
  if (!analysis.skillGaps.length) return <p className="text-sm text-ink-muted">No skill gaps recorded.</p>;
  return (
    <div className="space-y-3">
      {analysis.skillGaps.map((g, i) => (
        <div key={i} className="card flex gap-4 p-4">
          <span
            className={`badge h-fit ${
              g.importance === 'critical' ? 'bg-rose-50 text-rose-700' : 'bg-amber-50 text-amber-700'
            }`}
          >
            {g.importance}
          </span>
          <div>
            <p className="text-sm font-semibold text-ink">{g.skill}</p>
            <p className="mt-1 text-sm text-ink-soft">{g.howToLearn}</p>
          </div>
        </div>
      ))}
    </div>
  );
}
