import type { PlanDef } from './types';


export const FALLBACK_PLANS: PlanDef[] = [
  {
    id: 'free',
    name: 'Free',
    price: 0,
    tagline: 'Try it out',
    credits: 5,
    unlimitedCredits: false,
    maxResumes: 2,
    chatLimit: 4,
    unlimitedChat: false,
    features: { compare: false, analytics: false, interviews: false },
    priority: false,
    highlights: ['5 AI runs', '2 resumes', 'ATS match, tailoring & cover letters', '4 follow-up questions / analysis'],
  },
  {
    id: 'starter',
    name: 'Starter',
    price: 299,
    tagline: 'For an active job hunt',
    credits: 60,
    unlimitedCredits: false,
    maxResumes: 3,
    chatLimit: 12,
    unlimitedChat: false,
    features: { compare: false, analytics: false, interviews: true },
    priority: false,
    highlights: ['60 AI runs / month', '3 resumes', 'Everything in Free', 'Mock interviews', '12 follow-up questions / analysis'],
  },
  {
    id: 'pro',
    name: 'Pro',
    price: 499,
    tagline: 'Most popular',
    credits: 250,
    unlimitedCredits: false,
    maxResumes: 5,
    chatLimit: 40,
    unlimitedChat: false,
    features: { compare: true, analytics: false, interviews: true },
    priority: false,
    highlights: ['250 AI runs / month', '5 resumes', 'Everything in Starter', 'Resume comparison (best-fit picker)', '40 follow-up questions / analysis'],
  },
  {
    id: 'premium',
    name: 'Premium',
    price: 999,
    tagline: 'Everything, unlimited',
    credits: 100000,
    unlimitedCredits: true,
    maxResumes: 15,
    chatLimit: 100000,
    unlimitedChat: true,
    features: { compare: true, analytics: true, interviews: true },
    priority: true,
    highlights: ['Unlimited AI runs', '15 resumes', 'Everything in Pro', 'Personal analytics dashboard', 'Unlimited follow-up chat', 'Priority processing (no rate limits)'],
  },
];
